import React, { useState } from 'react';
import {
  X,
  CheckCircle2,
  Circle,
  Clock,
  BookOpen,
  FileText,
  Lightbulb,
  ChevronRight,
  Copy,
  Check,
  Download,
  Code,
  Layers,
} from 'lucide-react';
import type { LessonPlan } from '../types';

interface LessonDrawerProps {
  isOpen: boolean;
  onClose: () => void;
  plan: LessonPlan | null;
  activeModuleIndex: number;
}

export const LessonDrawer: React.FC<LessonDrawerProps> = ({
  isOpen,
  onClose,
  plan,
  activeModuleIndex,
}) => {
  const [activeTab, setActiveTab] = useState<'modules' | 'notes' | 'source'>('modules');
  const [copiedAll, setCopiedAll] = useState(false);
  const [copiedSectionIndex, setCopiedSectionIndex] = useState<number | null>(null);

  if (!isOpen) return null;

  if (!plan) {
    return (
      <aside className="fixed inset-y-0 right-0 z-30 w-96 max-w-[90vw] border-l border-[#44474f]/40 bg-[#111318]/95 shadow-2xl flex flex-col backdrop-blur-2xl animate-in slide-in-from-right duration-300">
        <div className="p-4 border-b border-[#44474f]/30 flex items-center justify-between">
          <h2 className="text-sm font-bold text-white font-['Outfit']">Lesson Curriculum</h2>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg bg-[#282a2f] hover:bg-[#33353a] text-[#8e9099] hover:text-white transition-all cursor-pointer"
          >
            <X className="w-4 h-4" />
          </button>
        </div>
        <div className="flex-1 flex flex-col items-center justify-center p-6 text-center text-[#8e9099]">
          <BookOpen className="w-10 h-10 text-[#44474f] mb-3" />
          <p className="text-sm font-medium text-slate-300">No active curriculum yet.</p>
          <p className="text-xs text-[#8e9099] mt-1">Start a lesson to generate modules and notes.</p>
        </div>
      </aside>
    );
  }

  const handleCopyAllNotes = () => {
    const fullNotes = [
      `# Study Guide: ${plan.topic}`,
      `Subject: ${plan.subject || 'General'} | Level: ${plan.level} | Estimated: ${plan.estimatedMinutes} mins`,
      '',
      '## Overview',
      plan.overview,
      '',
      '## Lecture Notes & Key Formulas',
      ...plan.lectureNotes.map((note, i) => `\n### Section ${i + 1}\n${note}`),
    ].join('\n');

    navigator.clipboard.writeText(fullNotes);
    setCopiedAll(true);
    setTimeout(() => setCopiedAll(false), 2000);
  };

  const handleCopySection = (text: string, index: number) => {
    navigator.clipboard.writeText(text);
    setCopiedSectionIndex(index);
    setTimeout(() => setCopiedSectionIndex(null), 2000);
  };

  const handleDownloadNotes = () => {
    const fullNotes = [
      `# Comprehensive Lecture Notes: ${plan.topic}`,
      `**Subject**: ${plan.subject || 'General'}  `,
      `**Level**: ${plan.level}  `,
      `**Duration**: ~${plan.estimatedMinutes} minutes  `,
      `**Generated By**: Rabbly AI Whiteboard Platform  `,
      '',
      '---',
      '',
      '## Executive Overview',
      plan.overview,
      '',
      '## Curriculum Checkpoints',
      ...plan.modules.map(
        (m, i) =>
          `### Module ${i + 1}: ${m.title} (${m.duration})\n${m.description}\n` +
          m.keyTakeaways.map((k) => `- ${k}`).join('\n')
      ),
      '',
      '## In-Depth Lecture Notes, Mathematical Formulations & Architecture',
      ...plan.lectureNotes.map((note) => `\n${note}\n`),
    ].join('\n');

    const blob = new Blob([fullNotes], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${plan.topic.toLowerCase().replace(/[^a-z0-9]/g, '_')}_notes.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <aside className="fixed inset-y-0 right-0 z-30 w-96 max-w-[90vw] border-l border-[#44474f]/40 bg-[#111318]/95 shadow-2xl flex flex-col backdrop-blur-2xl animate-in slide-in-from-right duration-300">
      {/* Drawer Header */}
      <div className="p-4 border-b border-[#44474f]/30 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="p-1.5 rounded-lg bg-[#0842a0]/30 text-[#a8c7fa] border border-[#a8c7fa]/30">
            <BookOpen className="w-4 h-4" />
          </div>
          <div>
            <h2 className="text-sm font-bold text-white font-['Outfit']">Lesson Curriculum</h2>
            <div className="flex items-center gap-2 text-[11px] text-[#8e9099] mt-0.5">
              {plan.subject && (
                <>
                  <span className="px-2 py-0.2 rounded-full bg-[#0842a0]/40 text-[#a8c7fa] border border-[#a8c7fa]/30 font-semibold font-mono text-[10px]">
                    {plan.subject}
                  </span>
                  <span>•</span>
                </>
              )}
              <span className="flex items-center gap-1">
                <Clock className="w-3 h-3" />
                {plan.estimatedMinutes} mins
              </span>
              <span>•</span>
              <span className="text-[#d0bcff] font-medium">{plan.level}</span>
            </div>
          </div>
        </div>

        <button
          onClick={onClose}
          className="p-1.5 rounded-lg bg-[#282a2f] hover:bg-[#33353a] text-[#8e9099] hover:text-white transition-all cursor-pointer"
        >
          <X className="w-4 h-4" />
        </button>
      </div>

      {/* Tabs */}
      <div className="flex border-b border-[#44474f]/30 px-4 pt-2 gap-4 text-xs font-semibold">
        <button
          onClick={() => setActiveTab('modules')}
          className={`pb-2.5 transition-all cursor-pointer border-b-2 flex items-center gap-1.5 ${
            activeTab === 'modules'
              ? 'border-[#a8c7fa] text-[#a8c7fa]'
              : 'border-transparent text-[#8e9099] hover:text-[#c4c6d0]'
          }`}
        >
          <Layers className="w-3.5 h-3.5" />
          <span>Modules ({plan.modules.length})</span>
        </button>
        <button
          onClick={() => setActiveTab('notes')}
          className={`pb-2.5 transition-all cursor-pointer border-b-2 flex items-center gap-1.5 ${
            activeTab === 'notes'
              ? 'border-[#a8c7fa] text-[#a8c7fa]'
              : 'border-transparent text-[#8e9099] hover:text-[#c4c6d0]'
          }`}
        >
          <FileText className="w-3.5 h-3.5" />
          <span>Study Notes ({plan.lectureNotes.length})</span>
        </button>
        <button
          onClick={() => setActiveTab('source')}
          className={`pb-2.5 transition-all cursor-pointer border-b-2 flex items-center gap-1.5 ${
            activeTab === 'source'
              ? 'border-[#a8c7fa] text-[#a8c7fa]'
              : 'border-transparent text-[#8e9099] hover:text-[#c4c6d0]'
          }`}
        >
          <Code className="w-3.5 h-3.5" />
          <span>Sources</span>
        </button>
      </div>

      {/* Content Area */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {activeTab === 'modules' && (
          <div className="space-y-3">
            <p className="text-xs text-[#c4c6d0] leading-relaxed bg-[#191c20] p-3 rounded-xl border border-[#44474f]/30">
              {plan.overview}
            </p>

            {plan.modules.map((mod, index) => {
              const isActive = index === activeModuleIndex;
              const isPast = index < activeModuleIndex;

              return (
                <div
                  key={mod.id}
                  className={`p-3.5 rounded-2xl border transition-all ${
                    isActive
                      ? 'bg-[#0842a0]/25 border-[#a8c7fa]/60 ring-1 ring-[#a8c7fa]/30 shadow-lg'
                      : isPast
                      ? 'bg-[#191c20]/60 border-[#44474f]/40 opacity-80'
                      : 'bg-[#1d2024] border-[#44474f]/50'
                  }`}
                >
                  <div className="flex items-start justify-between gap-2 mb-1.5">
                    <div className="flex items-center gap-2">
                      {isPast ? (
                        <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
                      ) : isActive ? (
                        <span className="relative flex h-3.5 w-3.5 shrink-0">
                          <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-[#a8c7fa] opacity-75"></span>
                          <span className="relative inline-flex rounded-full h-3.5 w-3.5 bg-[#a8c7fa]"></span>
                        </span>
                      ) : (
                        <Circle className="w-3.5 h-3.5 text-[#8e9099] shrink-0" />
                      )}
                      <h3 className={`text-xs font-bold ${isActive ? 'text-[#a8c7fa]' : 'text-[#e2e2e9]'}`}>
                        {mod.title}
                      </h3>
                    </div>
                    <span className="text-[10px] font-mono text-[#8e9099] shrink-0 px-1.5 py-0.5 rounded bg-[#111318]">
                      {mod.duration}
                    </span>
                  </div>

                  <p className="text-[11px] text-[#c4c6d0] ml-5 leading-relaxed mb-2">
                    {mod.description}
                  </p>

                  {/* Key takeaways */}
                  <div className="ml-5 space-y-1">
                    {mod.keyTakeaways.map((point, pIdx) => (
                      <div key={pIdx} className="flex items-start gap-1.5 text-[11px] text-slate-300">
                        <ChevronRight className="w-3 h-3 text-[#a8c7fa] shrink-0 mt-0.5" />
                        <span>{point}</span>
                      </div>
                    ))}
                  </div>
                </div>
              );
            })}
          </div>
        )}

        {activeTab === 'notes' && (
          <div className="space-y-3">
            {/* Quick Actions Bar */}
            <div className="flex items-center justify-between gap-2 p-2.5 rounded-xl bg-[#191c20] border border-[#44474f]/30">
              <span className="text-[11px] font-medium text-[#c4c6d0]">
                {plan.lectureNotes.length} Comprehensive Sections
              </span>

              <div className="flex items-center gap-1.5">
                <button
                  type="button"
                  onClick={handleCopyAllNotes}
                  className="px-2.5 py-1 rounded-lg bg-[#282a2f] hover:bg-[#33353a] text-[11px] font-semibold text-[#a8c7fa] hover:text-white flex items-center gap-1 transition-all cursor-pointer"
                  title="Copy full notes markdown"
                >
                  {copiedAll ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                  <span>{copiedAll ? 'Copied' : 'Copy All'}</span>
                </button>

                <button
                  type="button"
                  onClick={handleDownloadNotes}
                  className="px-2.5 py-1 rounded-lg bg-[#0842a0]/40 hover:bg-[#0842a0]/60 text-[11px] font-semibold text-[#a8c7fa] hover:text-white border border-[#a8c7fa]/30 flex items-center gap-1 transition-all cursor-pointer"
                  title="Download .md file"
                >
                  <Download className="w-3 h-3" />
                  <span>.md</span>
                </button>
              </div>
            </div>

            <div className="space-y-3">
              {plan.lectureNotes.map((note, index) => (
                <div
                  key={index}
                  className="p-3.5 rounded-2xl bg-[#1d2024] border border-[#44474f]/40 space-y-2 text-xs text-[#e2e2e9] shadow-sm relative group"
                >
                  <div className="flex items-center justify-between pb-1 border-b border-[#44474f]/20">
                    <span className="text-[10px] font-mono font-bold uppercase tracking-wider text-[#a8c7fa] flex items-center gap-1">
                      <Lightbulb className="w-3 h-3" />
                      Section #{index + 1}
                    </span>

                    <button
                      type="button"
                      onClick={() => handleCopySection(note, index)}
                      className="opacity-0 group-hover:opacity-100 p-1 rounded-md hover:bg-[#282a2f] text-[#8e9099] hover:text-white transition-opacity cursor-pointer"
                      title="Copy section"
                    >
                      {copiedSectionIndex === index ? (
                        <Check className="w-3 h-3 text-emerald-400" />
                      ) : (
                        <Copy className="w-3 h-3" />
                      )}
                    </button>
                  </div>

                  <div className="font-mono text-[11px] leading-relaxed whitespace-pre-wrap text-[#c4c6d0] overflow-x-auto">
                    {note}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {activeTab === 'source' && (
          <div className="space-y-3">
            <div className="p-3.5 rounded-2xl bg-[#191c20] border border-[#44474f]/30 space-y-2">
              <div className="flex items-center gap-2 text-xs font-semibold text-white">
                <FileText className="w-4 h-4 text-[#78f8e7]" />
                <span>Primary Learning Source & Citations</span>
              </div>
              <p className="text-xs text-[#c4c6d0] leading-relaxed">
                Topic: <span className="text-[#a8c7fa] font-semibold">{plan.topic}</span>
              </p>
            </div>

            {plan.sourceMaterials && plan.sourceMaterials.length > 0 ? (
              <div className="space-y-2.5">
                {plan.sourceMaterials.map((source, sIdx) => (
                  <div
                    key={source.id || sIdx}
                    className="p-3 rounded-xl bg-[#1d2024] border border-[#44474f]/40 space-y-1 text-xs"
                  >
                    <div className="flex items-center justify-between">
                      <span className="text-[10px] font-mono uppercase px-1.5 py-0.5 rounded bg-emerald-950/80 text-emerald-300 border border-emerald-800 font-bold">
                        {source.type}
                      </span>
                      {source.url && (
                        <a
                          href={source.url}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-[11px] text-[#a8c7fa] hover:text-white font-mono hover:underline"
                        >
                          Source Link ↗
                        </a>
                      )}
                    </div>
                    <h4 className="text-xs font-bold text-white mt-1">
                      {source.title}
                    </h4>
                    {source.snippet && (
                      <p className="text-[11px] text-[#c4c6d0] mt-1 leading-snug font-mono">
                        {source.snippet}
                      </p>
                    )}
                  </div>
                ))}
              </div>
            ) : (
              <div className="p-3 rounded-xl bg-[#191c20] border border-[#44474f]/30 text-[11px] text-[#8e9099] leading-relaxed font-mono">
                Knowledge graph initialized. Canonical textbooks, academic citations, and source notes synchronized with this session.
              </div>
            )}
          </div>
        )}
      </div>
    </aside>
  );
};

